// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTKTfT9yjiwXA5HmH2TXYOF4Swl6maK8',
    appId: '1:117666353326:web:cb1a4f1cfe5c53a3809d3f',
    messagingSenderId: '117666353326',
    projectId: 'alarm-optimus2727',
    authDomain: 'alarm-optimus2727.firebaseapp.com',
    storageBucket: 'alarm-optimus2727.firebasestorage.app',
    measurementId: 'G-DE6SYL0QY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5RPFaZdeMIwZ_KD5WjdaOgdeX54qfo0c',
    appId: '1:117666353326:android:ec90e5f75a1e4d42809d3f',
    messagingSenderId: '117666353326',
    projectId: 'alarm-optimus2727',
    storageBucket: 'alarm-optimus2727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYLNxTkLxXx2pogv36zJVgtS3UWGK1D4',
    appId: '1:117666353326:ios:ce6f78e8e211ad29809d3f',
    messagingSenderId: '117666353326',
    projectId: 'alarm-optimus2727',
    storageBucket: 'alarm-optimus2727.firebasestorage.app',
    iosBundleId: 'com.alarm.optimus2727',
  );
}
