// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHteeQwWIytiAdrs2_DWtDXAhYrvy3u0M',
    appId: '1:337345450183:web:24f85f971c9ecccdb3eee2',
    messagingSenderId: '337345450183',
    projectId: 'alarme-288bd',
    authDomain: 'alarme-288bd.firebaseapp.com',
    storageBucket: 'alarme-288bd.firebasestorage.app',
    measurementId: 'G-1820W035VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-qjonx89k1IsmpcjhgzPvrBSMJhld88',
    appId: '1:337345450183:android:18fcd98231a33885b3eee2',
    messagingSenderId: '337345450183',
    projectId: 'alarme-288bd',
    storageBucket: 'alarme-288bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbezwDuRjBIq7Qvd9vdO8pj9t81KKfzs0',
    appId: '1:337345450183:ios:7ad7bdcd1978fcfdb3eee2',
    messagingSenderId: '337345450183',
    projectId: 'alarme-288bd',
    storageBucket: 'alarme-288bd.firebasestorage.app',
    iosBundleId: 'com.scriptmatter.alarm',
  );

}